In [2]:
import numpy as np

### In this file we will go through the Devitt el al. paper (arXiv: 0905.2794v4) and derive and explain all of the math and theory to fully understand basic QEC

## ll. Preliminaries

### This section describes:
    (a) The basic structure of a qubit
    (b) Some general requirements of QEC

#### Suggest reading this section of the paper to understand the fundamentals of qubits and why we need QEC

In [24]:
# Pauli Operators
sigma_x = np.array([[0,1],[1,0]])
sigma_y = np.array([[0,1j],[-1j,0]])
sigma_z = np.array([[1,0],[0,-1]])
sigma_I = np.identity(2)
print('Below we show the Pauli Operators which can be used to describe any quantum gate on an individual qubit:')
print('Pauli-X: \n', sigma_x) 
print('Pauli-Y: \n', sigma_y)
print('Pauli-Z: \n', sigma_z)
print('Pauli-I: \n', sigma_I)

Below we show the Pauli Operators which can be used to describe any quantum gate on an individual qubit:
Pauli-X: 
 [[0 1]
 [1 0]]
Pauli-Y: 
 [[ 0.+0.j  0.+1.j]
 [-0.-1.j  0.+0.j]]
Pauli-Z: 
 [[ 1  0]
 [ 0 -1]]
Pauli-I: 
 [[1. 0.]
 [0. 1.]]


## lll. Quantum Errors: Cause and Effect

### In this section we consider different sources of error 
#### (coherent, environmental decoherence, and loss, leakage, measuremnt and initialization)
### We will apply these errors to two different algorithms.

### 1. A single qubit undergoing N identity opertations
$$\vert\psi_{final}\rangle = \prod_{i}^{N} I_{i} \vert0\rangle = \vert0\rangle $ Where $I \equiv \sigma_{I}$$ 

#### If a qubit is initially in the $\vert0\rangle $state then this operation in the basis $\vert0\rangle$, $\vert1\rangle$ would be $\vert0\rangle$
#### This can be shown with the code below:
#### Feel free to play with the initial state values and see what results :)

In [60]:
initial_state = np.array([1, 0]) # initalize initial state to |0>
n = 10 # number of times to apply the I operator (can be anything)
I_i = np.identity(2) # initialize I_i for i = 1 first

# Since we are only indexing over i we can multiply I_i with sigma_I n times to arrive at I_n final
for i in range(0,n):
    I_n = np.dot(I_i, sigma_I)

final_state = np.dot(I_n, initial_state)
print('Here we can see that the final state is |0> ')
print('Final State: ', final_state)

Here we can see that the final state is |0> 
Final State:  [1. 0.]


### 2. An algorithm of 3 gates acting on a qubit
$$\vert\psi\rangle = HIH\vert0\rangle = HI\frac{1}{\sqrt{2}}(\vert0\rangle + \vert1\rangle) = H\frac{1}{\sqrt{2}}(\vert0\rangle + \vert1\rangle) = \vert0\rangle$$
#### We can show the above case is correct by applying this algorithm to a single qubit in the $\vert0\rangle$ state:
###### Feel free to play with the initial state values and see what results :)

In [59]:
initial_state = np.array([1,0]) # initalize initial state to |0>
h = 1/np.sqrt(2)*np.array([[1,1],[1,-1]]) # set the hadamard operator 

# Below we perform the 3 gate operation and psi just represents the state of the qubit during the operations
psi = np.dot(h, inital_state) # apply the first hadamard gate
psi = np.dot(sigma_I, psi) # apply a wait stage with the I gate
final_state = np.dot(h, psi) # apply the second hadamard gate

print('Here we can see that the final state is |0> ')
print('Final State: ', (np.rint(final_state)).astype(int))

Here we can see that the final state is |0> 
Final State:  [1 0]


### A. Coherent Quantum Errors: Gates which are incorrectly applied:
#### This error is usually related to incorrect knowledge of the system dynamics, but it is coherent

### First we will consider an example which applies an incorrect rotation about the X-axis of the Bloch Sphere
$$ |\psi_{final}> = \prod_{k}^{N} e^{i\epsilon\sigma_{x}}|0> = \cos(N\epsilon)|0> + i\sin(N\epsilon)|1>$$

#### Now we will measure the system in the $\vert0\rangle$, $\vert1\rangle$ basis
#### Due to the coherent quantum errors below is the probability of measuing the system in $\vert0\rangle$ or $\vert1\rangle$:
$$ P(\vert0\rangle) = \cos^2(N\epsilon) \approx 1 - (N\epsilon)^2 $$
$$ P(\vert1\rangle) = \sin^2(N\epsilon) \approx (N\epsilon)^2$$
#### Thus the probability of error is 
$$ p_{error} \approx (N\epsilon)^2$$
### Below we can see a coherent quantum error acting on the initial state with arbitrary $\epsilon$ and calculate the error due to the X-rotation error N times

In [62]:
initial_state = np.array([1,0]) # initalize initial state to |0>
epsilon = 3 # arbitrary epsilon is set
n = 10 # arbitrary N is set
initial_error_operator = error_operator = np.exp(1j*epsilon*sigma_x)
# Since we are only indexing over k we can multiply the intitial error operator with the current error 
# operator n times to arrive at the final error operator after n
for k in range(0,n):
    error_operator = np.dot(error_operator, initial_error_operator)

final_state = np.dot(error_operator, initial_state)
print('Final State: ', final_state)


Final State:  [ 709.03379352-699.68180095j -709.03379352+699.68180095j]


In [64]:
initial_state = np.array([1,0]) # initalize initial state to |0>
epsilon = 3 # arbitrary epsilon is set
n = 10 # arbitrary N is set
initial_error_operator = error_operator = np.exp(1j*epsilon*sigma_x)
# Since we are only indexing over k we can multiply the intitial error operator with the current error 
# operator n times to arrive at the final error operator after n
for k in range(0,n):
    error_operator = np.dot(error_operator, initial_error_operator)

final_state = np.dot(np.cos(n*epsilon), initial_state) + np.dot(1j*np.sin(n*epsilon), np.array([0,1]))
print('Final State: ', final_state)

Final State:  [0.15425145+0.j         0.        -0.98803162j]


In [ ]:
#C. Simple models of loss, leakage, measurement and
initialization

#Various error sources in quantum systems, including qubit initialization, measurement errors, qubit loss, and qubit leakage, can be modeled similarly.



#Coherent control errors, environmental decoherence, and other error channels can be modeled either coherently or incoherently, depending on the underlying physical mechanisms.

#Examples of these error sources are commonly used in quantum error correction (QEC) analysis and are applicable to a wide range of systems.

#Measurement errors can be treated as incoherent effects, similar to environmental decoherence, and can be described using positive operator value measures (POVM's).


$$F_0 = \left ( 1-p_m \right ) |0><0| + p_m |1><1|\\
F_1 = \left ( 1-p_m \right ) |1><1| + p_m |0><0|$$
#Eq 14

#where p_m is the probability of measurement error.

#Second method is to apply the following mapping to qubit ( I'll have use simpler phrases)


$$p \to p' = \left ( 1-p_m \right )\ p + p_M X pX$$
#Eq 15

#where a measuement happens in the (|0>,|1>) basis.

#Both models give the same probabilties.


$$Tr(F_0 p)=\left( 1-p_M \right)Tr\left( A_0 p \right))+ p_MTr(A_1p)),\\
Tr(F_1 p)=\left( 1-p_M \right)Tr\left( A_1 p \right))+ p_MTr(A_0p)),\\
\\$$
#Eq 16

$$\\
Tr(A_0 p')=\left( 1-p_M \right)Tr\left(A_0 p \right))+ p_MTr(XA_0 X_p))\\
= \left( 1-p_M \right)Tr\left(A_0 p \right))+ p_MTr(A_1p))\\
Tr(A_1 p')=\left( 1-p_M \right)Tr\left(A_1 p \right))+ p_MTr(XA_1 X_p))\\
= \left( 1-p_M \right)Tr\left(A_1 p \right))+ p_MTr(A_0p))\\$$
#Eq 17

#Keep in mind that p_M is the probability of the measurement, so any method above will result in the same probabilties for any given p_M. 
#Only difference is:  state qubit is projected to.



## IV. The 3-Qubit Code: A good starting point for quantum error correction

## V. The 9-Qubit Code: The first full quantum code

## Vl. Quantum Error Detection

## Vll. Stabiliser Formalism

## Vlll. Quantum Error Correction with Stabiliser Codes

## lX. Digitization of Quantum Errors

## X. Fault Tolerant Quantum Error Correction and the Threashold Theorem

## Xl. Fault Tolerant Operations on Encoded Data

## Xll. Fault Tolerant Gate Design for Logical State Preparation

## Xlll. Loss Protection

## XlV. Some Modern Develpments in Quantum Error Correction